# Generated by Django 4.1.3 on 2022-11-13 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_dueno_residencia_dueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondecia',
            name='conserje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
